version: '2'
services:
  eureka-dt-server:
    build: eureka-dt-server
    ports:
      - 8761:8761

  user-service:
    build: user-service
    ports:
      - 8770:8770

  config-server:
    build: config-server
    ports:
      - 8767:8767

  sleuth-server:
    build: sleuth-server
    ports:
    - 9411:9411


