spring:
  application:
    name: edge-service
server:
  port: 9999
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    account-service: /account/**
    user-account-service: /user/**
    catalog-service: /catalog/**
# 提高延时设置 elevate timeout settings, 避免因为延时造成失败
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://47.101.147.30:8761/eureka/